package tandemplatform;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.QUESTION_MESSAGE;
import static javax.swing.JOptionPane.YES_NO_CANCEL_OPTION;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Marcos Guo
 */
public class ProfileFrame extends javax.swing.JFrame {

    /**
     * Creates new form ProfileFrame
     */
    private ArrayList <User> matchArray = new ArrayList();
    
    public ProfileFrame() {
        initComponents();
    }
    
    public void setUser(User user){
        this.user = user;
    }
    
    public void setUsername(String username){
       jLabelUser.setText(username);
    }
   
     public void setName(String name)
    {
        newName.setText(name);
    }
    public void setSurname(String surname)
    {
        newSurname.setText(surname);
    }
    public void setPassword(String password)
    {
        newPw.setText(password);
    }

    public void setBirthdate(String birthDate)
    {
        newBirth.setText(birthDate);
    }
    public void setOccupation(String occupation)
    {
        comboOc.setSelectedItem(occupation);
    }
    public void setEmail(String email)
    {
        newEmail.setText(email);
    }
    public void setCOO(String countryOfOrigin)
    {
        newFrom.setText(countryOfOrigin);
    }
    public void setCOR(String countryOfResidence)
    {
        newLiving.setText(countryOfResidence);
    }
    
    public void setClient(ClientClass clientclass){
        this.clientclass = clientclass;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelWelcome = new javax.swing.JLabel();
        jLabelUser = new javax.swing.JLabel();
        newName = new javax.swing.JTextField();
        jLabelSurname = new javax.swing.JLabel();
        newSurname = new javax.swing.JTextField();
        jLabelUsername = new javax.swing.JLabel();
        newUsername = new javax.swing.JTextField();
        jLabelPw = new javax.swing.JLabel();
        jLabelBirth = new javax.swing.JLabel();
        newBirth = new javax.swing.JTextField();
        jLabelOccupation = new javax.swing.JLabel();
        comboOc = new javax.swing.JComboBox<>();
        jLabelEmail = new javax.swing.JLabel();
        newEmail = new javax.swing.JTextField();
        jLabelFrom = new javax.swing.JLabel();
        newFrom = new javax.swing.JTextField();
        jLabelLiving = new javax.swing.JLabel();
        newLiving = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        ButtonUpdate = new javax.swing.JButton();
        newPw = new javax.swing.JPasswordField();
        ButtonMatch = new javax.swing.JButton();
        ButtonLanguages = new javax.swing.JButton();
        ButtonExit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelWelcome.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabelWelcome.setText("Welcome,");

        jLabelUser.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabelUser.setText("username");

        newName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        newName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newNameActionPerformed(evt);
            }
        });

        jLabelSurname.setText("SURNAME:");

        newSurname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newSurnameActionPerformed(evt);
            }
        });

        jLabelUsername.setText("USERNAME:");

        newUsername.setEditable(false);

        jLabelPw.setText("PASSWORD:");

        jLabelBirth.setText("BIRTH DATE:");

        jLabelOccupation.setText("OCCUPATION:");

        comboOc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Student", "Unemployed", "Physician", "Lawyer", "Engineer", "Architect", "Other" }));

        jLabelEmail.setText("EMAIL:");

        newEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newEmailActionPerformed(evt);
            }
        });

        jLabelFrom.setText("FROM:");

        jLabelLiving.setText("LIVING:");

        ButtonUpdate.setText("UPDATE");

        ButtonMatch.setText("MATCH");
        ButtonMatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MatchButtonActionPerformed(evt);
            }
        });

        ButtonLanguages.setText("MY LANGUAGES");
        ButtonLanguages.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LanguageButtonActionPerformed(evt);
            }
        });

        ButtonExit.setText("LOG OUT");
        ButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });
        jLabel2.setText("NAME:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelOccupation)
                            .addComponent(jLabelEmail)
                            .addComponent(jLabelFrom)
                            .addComponent(jLabelLiving)
                            .addComponent(jLabelSurname)
                            .addComponent(jLabelUsername)
                            .addComponent(jLabelPw)
                            .addComponent(jLabelBirth)
                            .addComponent(jLabel2))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(newEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(newFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(newLiving, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(newPw, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(newName, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(newSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(newUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(newBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38)
                                .addComponent(jLabel1)
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(ButtonExit, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                                    .addComponent(ButtonMatch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(comboOc, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabelWelcome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelUser))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ButtonUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                            .addComponent(ButtonLanguages, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(54, 54, 54))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {comboOc, newBirth, newEmail, newFrom, newLiving, newName, newPw, newSurname, newUsername});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelWelcome)
                            .addComponent(jLabelUser)
                            .addComponent(ButtonExit))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(newName, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelSurname)
                                    .addComponent(newSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelUsername)
                            .addComponent(newUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPw)
                            .addComponent(newPw, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(ButtonMatch, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelBirth))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelOccupation)
                    .addComponent(comboOc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelEmail)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelFrom))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(newEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(newFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelLiving)
                    .addComponent(newLiving, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(ButtonUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonLanguages)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newSurnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newSurnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newSurnameActionPerformed

    private void newNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newNameActionPerformed

    private void newEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newEmailActionPerformed
    private void LanguageButtonActionPerformed(java.awt.event.ActionEvent evt) {                                         
        LangFrame langFrame = new LangFrame(user);
        langFrame.setVisible(true);
        langFrame.setLocationRelativeTo(null);
        langFrame.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        //UPDATE DO BANCO DE DADOS SqlComms
    }
    private void MatchButtonActionPerformed(java.awt.event.ActionEvent evt) {                                         
        String[] langs = new String[]{"Portuguese", "English", "German", "Japanese", "Mandarin", "Corean", "Spanish", "Arabic", "Cancel" };
        String message = "Please, select the language which you'd like to learn now!";
        int langOption = JOptionPane.showOptionDialog(null, message, "TandemPlatform", YES_NO_CANCEL_OPTION, QUESTION_MESSAGE,null, langs,null);
        if (langOption!= langs.length)
        {
            langOption = langOption+1;
            clientclass.sendMatch(langOption, user, 3, 5);
            matchArray = clientclass.receiveMatch();
            MatchFrame1 matchFrame = new MatchFrame1(matchArray);
            matchFrame.setVisible(true);
            matchFrame.setLocationRelativeTo(null);
            matchFrame.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        }
        //UPDATE DO BANCO DE DADOS SqlComms
    }
    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) 
    {
        this.dispose();
    }
    private ClientClass clientclass;
    private String username;
    private User user;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonExit;
    private javax.swing.JButton ButtonLanguages;
    private javax.swing.JButton ButtonMatch;
    private javax.swing.JButton ButtonUpdate;
    private javax.swing.JComboBox<String> comboOc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelBirth;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelFrom;
    private javax.swing.JLabel jLabelLiving;
    private javax.swing.JLabel jLabelOccupation;
    private javax.swing.JLabel jLabelPw;
    private javax.swing.JLabel jLabelSurname;
    private javax.swing.JLabel jLabelUser;
    private javax.swing.JLabel jLabelUsername;
    private javax.swing.JLabel jLabelWelcome;
    private javax.swing.JTextField newBirth;
    private javax.swing.JTextField newEmail;
    private javax.swing.JTextField newFrom;
    private javax.swing.JTextField newLiving;
    private javax.swing.JTextField newName;
    private javax.swing.JPasswordField newPw;
    private javax.swing.JTextField newSurname;
    private javax.swing.JTextField newUsername;
    // End of variables declaration//GEN-END:variables
}
